safe: true
port: 4000
baseurl: /
url: http://localhost:4000

markdown: maruku
pygments: true
permalink: date
maruku:
    use_tex:    false
    use_divs:   false
    png_engine: blantex
    png_dir:    images/latex
    png_url:    /images/latex
